name: run-cpack
description: 'GitHub action to run CPack'
author: flagarde

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  binary_dir:
    description: 'Path to directory which CMake will use as the root of build directory.'
    required: false
    default: '../build'
  generators:
    description: 'List of generator names'
    required: true
    default: 'NSIS64'

branding:
  icon: 'settings'
  color: 'green'
