name: run-cpack
description: 'GitHub action to run CPack'
author: flagarde

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  binary_dir:
    description: 'Path to directory which CMake will use as the root of build directory.'
    required: false
    default: '../build'
  generators:
    description: 'List of generator names'
    required: true
    default: 'NSIS64'
  configurations:
    description: 'Specify the project configuration(s) to be packaged (e.g. Debug, Release, etc.)'
    required: false
    default: ''
  packages_directory:
    description: 'Override/define CPACK_PACKAGE_DIRECTORY, which controls the directory where CPack will perform its packaging work.'
    required: false
    default: ''

branding:
  icon: 'settings'
  color: 'green'
