name: macOS

on:
  push:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    name: CMake v3.${{ matrix.cmake_version }}
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout tests repository
        uses: actions/checkout@v4
        with:
          repository: cmake-tools/runs.test
          path: tests

      - name: ⬇️ Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.${{ matrix.cmake_version }}
          ninjaVersion: ^1
      
      - name: ⚙️ run-cmake (configure)
        uses: cmake-tools/run-cmake@v0-alpha
        id: configure
        with:
          mode: configure
          generator: Ninja
          install_prefix: './MyInstallPrefix'
          source_dir: './tests'

      - name: 🛠️ run-cmake (build)
        uses: cmake-tools/run-cmake@v0-alpha
        id: build
        with:
          mode: build
          clean_first: true
          build_verbose: true

      - name: 📦 run-cpack
        uses: ./
        id: test
        with:
          generators: 'STGZ'
        
